org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m

# Gradle Configuration
gradle.startParameter.excludedTaskNames=lint

# API configuration
API_BASE_URL=http://your-vps-url.com

android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true

# R8
android.enableR8=true
android.useModuleInspectionForR8=true

kotlin.code.style=official
